// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prediccion.acciones.domain;

import com.prediccion.acciones.domain.CompanyProperty;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CompanyProperty_Roo_Configurable {
    
    declare @type: CompanyProperty: @Configurable;
    
}
