// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prediccion.acciones.domain;

import com.prediccion.acciones.domain.Company;
import com.prediccion.acciones.domain.CompanyDataOnDemand;
import com.prediccion.acciones.service.CompanyService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CompanyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompanyDataOnDemand: @Component;
    
    private Random CompanyDataOnDemand.rnd = new SecureRandom();
    
    private List<Company> CompanyDataOnDemand.data;
    
    @Autowired
    CompanyService CompanyDataOnDemand.companyService;
    
    public Company CompanyDataOnDemand.getNewTransientCompany(int index) {
        Company obj = new Company();
        setCompanyId(obj, index);
        setExchange(obj, index);
        setLocalCurrencySymbol(obj, index);
        setMarket(obj, index);
        setMaxForecastValue(obj, index);
        setMedForecastValue(obj, index);
        setMinForecastValue(obj, index);
        setTicker(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void CompanyDataOnDemand.setCompanyId(Company obj, int index) {
        String companyId = "companyId_" + index;
        obj.setCompanyId(companyId);
    }
    
    public void CompanyDataOnDemand.setExchange(Company obj, int index) {
        String exchange = "exchange_" + index;
        obj.setExchange(exchange);
    }
    
    public void CompanyDataOnDemand.setLocalCurrencySymbol(Company obj, int index) {
        String localCurrencySymbol = "localCurrencySymbol_" + index;
        obj.setLocalCurrencySymbol(localCurrencySymbol);
    }
    
    public void CompanyDataOnDemand.setMarket(Company obj, int index) {
        String market = "market_" + index;
        obj.setMarket(market);
    }
    
    public void CompanyDataOnDemand.setMaxForecastValue(Company obj, int index) {
        Double maxForecastValue = new Integer(index).doubleValue();
        obj.setMaxForecastValue(maxForecastValue);
    }
    
    public void CompanyDataOnDemand.setMedForecastValue(Company obj, int index) {
        Double medForecastValue = new Integer(index).doubleValue();
        obj.setMedForecastValue(medForecastValue);
    }
    
    public void CompanyDataOnDemand.setMinForecastValue(Company obj, int index) {
        Double minForecastValue = new Integer(index).doubleValue();
        obj.setMinForecastValue(minForecastValue);
    }
    
    public void CompanyDataOnDemand.setTicker(Company obj, int index) {
        String ticker = "ticker_" + index;
        obj.setTicker(ticker);
    }
    
    public void CompanyDataOnDemand.setTitle(Company obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Company CompanyDataOnDemand.getSpecificCompany(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Company obj = data.get(index);
        Long id = obj.getId();
        return companyService.findCompany(id);
    }
    
    public Company CompanyDataOnDemand.getRandomCompany() {
        init();
        Company obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return companyService.findCompany(id);
    }
    
    public boolean CompanyDataOnDemand.modifyCompany(Company obj) {
        return false;
    }
    
    public void CompanyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = companyService.findCompanyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Company' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Company>();
        for (int i = 0; i < 10; i++) {
            Company obj = getNewTransientCompany(i);
            try {
                companyService.saveCompany(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
